-- MySQL Script generated by MySQL Workbench
-- 03/15/18 15:31:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mycvproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycvproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycvproject` DEFAULT CHARACTER SET utf8 ;
USE `mycvproject` ;

-- -----------------------------------------------------
-- Table `mycvproject`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`person` (
  `idperson` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `Address` VARCHAR(90) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`language` (
  `idlanguage` INT NOT NULL,
  `languageName` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idlanguage`, `person_idperson`),
  INDEX `fk_language_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_language_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`course` (
  `idcourse` INT NOT NULL,
  `courseName` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idcourse`, `person_idperson`),
  INDEX `fk_course_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_course_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`hobby` (
  `idhobby` INT NOT NULL,
  `hobbyName` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idhobby`, `person_idperson`),
  INDEX `fk_hobby_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_hobby_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`site` (
  `idsite` INT NOT NULL,
  `siteAddress` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idsite`, `person_idperson`),
  INDEX `fk_site_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_site_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`app` (
  `idapp` INT NOT NULL,
  `appName` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idapp`, `person_idperson`),
  INDEX `fk_app_person_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_app_person`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycvproject`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycvproject`.`project` (
  `idproject` INT NOT NULL,
  `projectName` VARCHAR(45) NULL,
  `person_idperson` INT NOT NULL,
  PRIMARY KEY (`idproject`, `person_idperson`),
  INDEX `fk_project_person1_idx` (`person_idperson` ASC),
  CONSTRAINT `fk_project_person1`
    FOREIGN KEY (`person_idperson`)
    REFERENCES `mycvproject`.`person` (`idperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
